###############################################################################
#   @author       :   ArveVM 
#   @date         :   16.march.2022
#   @integration  :   HACS; Min_renovasjon
#   @description  :   Norwegian garbaage-pickup-schedule
#   @basic concept: 
#      Some Norwegian garbage companies have got together and created
#      an app to enable customers warnings of regular and changed 
#      garbage pick-up-times.
#
#   Then some smart people wanted this data in HA, and one solution after
#   another ended up with this one approved onto the HACS-
#   Instalation via HACS -> /config/custom_components/min_renovasjon   
#   some config in HACS-intgration ?
#
#   Again, tip and shitload of guiding from mrRR
# 
#   further info: https://github.com/Danielhiversen/home_assistant_min_renovasjon
#
###############################################################################


# First setup the Integration according to requirements in documentation: 
# (this define our home-address/garbage-pickup-location)
min_renovasjon:
  street_name: !secret min_renovasjon_street_name
  house_no: !secret min_renovasjon_house_no
  street_code: !secret min_renovasjon_street_code
  county_id: !secret min_renovasjon_county_id
  date_format: "%d.%m.%Y"


# Then add the required sensor for the Integration to populate sensors 
# for our home (Integration will provide one new sensor for each type of garbage)
sensor:
  - platform: min_renovasjon
    fraction_id:
      - 1           # sensor.restavfall
      - 2           # sensor.papp_papir_plast
      - 3           # sensor.matavfall
      - 4           # sensor.glas_metallemballasje
# AVM: not sure about the naming of sensor, since my sensors are named differently 
# that the ones in the integration-documentation,, perhaps 'fractions' are 
# named differently for each garbage-company ?     
# (see my 'papp&papir&plast' which is one sensor, but in documentation separated
# I guess this is because of my company's specific pickup-schedule)


# Then some sensors to calculate how many days until next pickup for each type garbage
template:
  - sensor:
      - name: min_renovasjon_next_restavfall
        unique_id: min_renovasjon_next_restavfall
        icon: mdi:trash-can
        state: >
          {% set seconds = as_timestamp(strptime(states('sensor.restavfall'),'%d.%m.%Y')) - as_timestamp(now().replace(hour=0, minute=0, second=0)) %}
          {{(seconds / 86400)|round()}} Days

      - name: min_renovasjon_next_papir
        icon: mdi:trash-can
        state: >
          {% set seconds = as_timestamp(strptime(states('sensor.papp_papir_plast'),'%d.%m.%Y')) - as_timestamp(now().replace(hour=0, minute=0, second=0)) %}
          {{(seconds / 86400)|round()}} Days

      - name: min_renovasjon_next_mat
        icon: mdi:trash-can
        state: >
          {% set seconds = as_timestamp(strptime(states('sensor.matavfall'),'%d.%m.%Y')) - as_timestamp(now().replace(hour=0, minute=0, second=0)) %}
          {{(seconds / 86400)|round()}} Days

      - name: min_renovasjon_next_glass_metall
        icon: mdi:trash-can
        state: >
          {% set seconds = as_timestamp(strptime(states('sensor.glas_metallemballasje'),'%d.%m.%Y')) - as_timestamp(now().replace(hour=0, minute=0, second=0)) %}
          {{(seconds / 86400)|round()}} Days

#the end