###############################################################################
#   @author       :   ArveVM 
#   @date         :   15.march.2022
#   @integration  :   Sensor
#   @description  :   enable powerful functionality!
#   @basic concept: 
#      enable sensor functionality, 
#      create a folder for .yaml-files with sensors
#
#   Guess I will prefer to create sensor within  each solution - but you never know
#
#   Tip and shitload of guiding from mrRR, part of the v2 of my splitting documentation
# 
#   further info: https://www.home-assistant.io/integrations/sensor
#
###############################################################################



sensor: !include_dir_list ../../entities/sensor